// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxwbtsxhrdowooheleti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4d2J0c3hocmRvd29vaGVsZXRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTgxMzYsImV4cCI6MjA2OTg5NDEzNn0.nFPlyDRsOyCWNBvujH4Hgd9dZT86-VK5S7x6Wroj2t4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});