// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlyroywtpvvdfjithdro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRseXJveXd0cHZ2ZGZqaXRoZHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDEwNzksImV4cCI6MjA3MjYxNzA3OX0.asnGceWYIyUaxKjX1PaJ4Wue3oXjQceNTleqUG7892g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});